version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - .:/app
    restart: on-failure
